---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  tests:
    name: Run tests
    uses: ./.github/workflows/tests.yml
